[project]
name = "paperclip-schemas"
version = "0.1.0"
description = "Shared data models & JSON Schemas for Paperclip"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pydantic>=2.7"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
