from __future__ import annotations

import csv
from datetime import datetime
from io import StringIO
from typing import Iterable, Mapping, Any

from captures.exporters import bibtex_entry_for, ris_lines_for
from captures.models import Capture
from captures.types import CSL
from captures.views.common import _authors_intext, _journal_full


def csv_for_all_captures() -> str:
    """
    CSV export for all captures, matching the current capture_export behavior.
    """
    buf = StringIO()
    w = csv.writer(buf)
    w.writerow(["id", "title", "authors_intext", "year", "journal_short", "doi", "url"])
    for c in Capture.objects.all().order_by("-created_at"):
        meta: Mapping[str, Any] = c.meta or {}
        csl: CSL | Mapping[str, Any] = c.csl or {}
        title = (
            c.title
            or meta.get("title")
            or ((csl.get("title") if isinstance(csl, Mapping) else "") or "")
            or c.url
            or ""
        ).strip() or "(Untitled)"
        authors = _authors_intext(meta, csl)
        j_full = _journal_full(meta, csl)
        j_short = j_full
        doi = (
            c.doi
            or meta.get("doi")
            or ((csl.get("DOI") if isinstance(csl, Mapping) else "") or "")
            or ""
        ).strip()
        w.writerow([str(c.id), title, authors, c.year, j_short, doi, c.url or ""])
    return buf.getvalue()


def bibtex_for_captures(caps: Iterable[Capture]) -> str:
    """
    Build a BibTeX export payload for a sequence of captures.
    """
    entries = [bibtex_entry_for(c) for c in caps]
    return (
        "% Generated by Paperclip\n% Exported: "
        + datetime.utcnow().isoformat(timespec="seconds")
        + "Z\n\n"
        + "\n\n".join(entries)
        + "\n"
    )


def ris_for_captures(caps: Iterable[Capture]) -> str:
    """
    Build a RIS export payload for a sequence of captures.
    """
    blocks = ["\n".join(ris_lines_for(c)) for c in caps]
    return "\n".join(blocks) + "\n"
