# Ruff = linter + import sorter (+ optional formatter if you later want to drop Black)
target-version = "py311"
line-length = 100

extend-exclude = [
  "data",
  "staticfiles",
  "node_modules",
  ".venv",
  "env",
  "venv",
  "services/server/**/migrations",
]

[lint]
# E/F/W: pycodestyle/pyflakes; B: bugbear; I: isort; UP: pyupgrade; C4: comprehensions; SIM: simplify; RUF: ruff extras
select = ["E", "F", "W", "B", "I", "UP", "C4", "SIM", "RUF"]
ignore = ["E203"]  # keep Black compatibility for slicing spacing

[lint.per-file-ignores]
"**/migrations/*.py" = ["ALL"]

[lint.isort]
known-first-party = ["analysis", "captures", "paperclip", "paperclip_schemas", "paperclip_parser"]
