# Generated by Django 5.2.6 on 2025-09-28 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.CharField(blank=True, max_length=1000)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("year", models.CharField(blank=True, max_length=12)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("csl", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_id", models.CharField(blank=True, max_length=100)),
                ("raw", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("url", models.CharField(blank=True, max_length=1000)),
                ("issued_year", models.CharField(blank=True, max_length=12)),
                ("container_title", models.CharField(blank=True, max_length=500)),
                ("authors", models.JSONField(blank=True, default=list)),
                ("csl", models.JSONField(blank=True, default=dict)),
                ("volume", models.CharField(blank=True, max_length=50)),
                ("issue", models.CharField(blank=True, max_length=50)),
                ("pages", models.CharField(blank=True, max_length=50)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("issn", models.CharField(blank=True, max_length=50)),
                ("isbn", models.CharField(blank=True, max_length=50)),
                ("bibtex", models.TextField(blank=True)),
                ("apa", models.TextField(blank=True)),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="captures.capture",
                    ),
                ),
            ],
        ),
    ]
