# Generated by Django 5.2.6 on 2025-09-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField()),
                ('dom_html', models.TextField()),
                ('content_html', models.TextField()),
                ('markdown', models.TextField()),
                ('meta', models.JSONField(default=dict)),
                ('csl', models.JSONField(default=dict)),
                ('figures', models.JSONField(default=list)),
                ('tables', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw', models.TextField()),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('apa', models.TextField(blank=True, null=True)),
                ('csl', models.JSONField(default=dict)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='paperclip.capture')),
            ],
        ),
    ]
