# Generated by Django 5.2.6 on 2025-09-23 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('doi', models.CharField(blank=True, max_length=256)),
                ('year', models.CharField(blank=True, max_length=8)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('csl', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('raw', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('issued_year', models.CharField(blank=True, max_length=8)),
                ('container_title', models.CharField(blank=True, max_length=512)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('csl', models.JSONField(blank=True, default=dict)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='captures.capture')),
            ],
        ),
    ]
