# Generated by Django 5.2.6 on 2025-09-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='apa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='bibtex',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='isbn',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='reference',
            name='issn',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='reference',
            name='issue',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reference',
            name='pages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reference',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reference',
            name='volume',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
