[project]
name = "paperclip-parser"
version = "0.1.0"
description = "HTML -> ServerParsed normalizer"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "beautifulsoup4>=4.12",
  "markdownify>=0.12",
  "paperclip-schemas>=0.1.0"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
