[project]
name = "paperclip-worker"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "requests>=2.32",
  "paperclip-schemas>=0.1.0"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
