name: Lint & Typecheck

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements-dev.txt

      - name: Black (check)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .
